config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  resources :contact, only: [:create]
  root "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name, validate: true
  attribute :email, validate: true
  attribute :message, validate: true

  def headers
    { 
      subject: "Contact Form: #{name}",
      to: "george.kettle@icloud.com",
      from: %("#{name}" <#{email}>)
    }
  end
end

app/models/contact_form.rb
class ContactForm < MailForm::Base
  attribute :name, validate: true
  attribute :email, validate: true
  attribute :content, validate: true

  def headers
    { 
      subject: "Contact Form: #{name}",
      to: "george.kettle@icloud.com",
      from: %("#{name}" <#{email}>)
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def create
    @contact = Contact.new(contact_params)

    if @contact.deliver
      redirect_to root_path, notice: "Thanks for contacting us!"
    else
      redirect_to root_path, alert: "There was an error sending your message."
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :email, :message)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @contact = Contact.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MailForm</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%# Render flashes if any %>
    <% if notice %>
      <p class="text-white bg-amber-500 p-2 rounded"><%= notice %></p>
    <% elsif alert %>
      <p class="text-white bg-red-500 p-2 rounded"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Contact us</h1>
<p>Send us an email and we will be in touch shortly</p>

<%= form_for :contact, url: contact_index_path do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br/>
  <%= f.label :email %>
  <%= f.text_field :email %><br/>
  <%= f.label :message %>
  <%= f.text_area :message %>
  <%= f.submit %>
<% end %>